"""Regenerate INDEX.md from the markdown files in the repository.

Lists every tracked or new (untracked but not ignored) .md file as a nested
tree. 09_MANUSCRIPTS is shown as a placeholder only, because it is
gitignored. Writes the file only when its content changes.

Usage:  python scripts/build_index.py [--check]
        --check  exit 1 if INDEX.md is out of date, without writing it
"""

import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "INDEX.md")
MANUSCRIPTS = "09_MANUSCRIPTS"
SKIP = {"INDEX.md"}


def markdown_files():
    out = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z", "--", "*.md"],
        cwd=ROOT, capture_output=True, check=True,
    ).stdout.decode("utf-8")
    paths = {p for p in out.split("\0") if p}
    return sorted(
        p for p in paths
        if p not in SKIP
        and not p.startswith(MANUSCRIPTS + "/")
        and not p.startswith(".")
        and "/." not in p
        and os.path.exists(os.path.join(ROOT, p))
    )


def build_tree(paths):
    tree = {"files": [], "dirs": {}}
    for p in paths:
        node = tree
        *dirs, name = p.split("/")
        for d in dirs:
            node = node["dirs"].setdefault(d, {"files": [], "dirs": {}})
        node["files"].append((name, p))
    return tree


def count_dirs(node):
    return sum(1 + count_dirs(child) for child in node["dirs"].values())


def manuscript_stanza(indent):
    pad = "  " * indent
    lines = [f"{pad}- **{MANUSCRIPTS}/**",
             f"{pad}  - *(gitignored — manuscript drafts stay local-only, not tracked in this repo)*"]
    base = os.path.join(ROOT, MANUSCRIPTS)
    if os.path.isdir(base):
        for d in sorted(os.listdir(base)):
            if os.path.isdir(os.path.join(base, d)):
                lines.append(f"{pad}  - **{d}/**")
    return lines


def render(node, indent, lines, top=False):
    pad = "  " * indent
    for name, path in sorted(node["files"]):
        lines.append(f"{pad}- [{name}]({path})")
    if top and node["files"]:
        lines.append("")
    names = sorted(node["dirs"])
    if top and os.path.isdir(os.path.join(ROOT, MANUSCRIPTS)):
        names = sorted(names + [MANUSCRIPTS])
    for d in names:
        if top and d == MANUSCRIPTS:
            lines.extend(manuscript_stanza(indent))
            continue
        lines.append(f"{pad}- **{d}/**")
        render(node["dirs"][d], indent + 1, lines)


def generate():
    paths = markdown_files()
    tree = build_tree(paths)
    lines = [
        "# Project Index",
        "",
        "Complete folder and file structure for **The Veilward Chronicles**. Every entry links to the corresponding file.",
        "",
        f"*{len(paths)} markdown files across {count_dirs(tree)} folders. "
        "Auto-generated by `scripts/build_index.py` — do not edit by hand. "
        "(09_MANUSCRIPTS is gitignored and excluded from this count.)*",
        "",
    ]
    render(tree, 0, lines, top=True)
    return "\n".join(lines) + "\n"


def main():
    new = generate()
    try:
        with open(INDEX, encoding="utf-8", newline="") as f:
            old = f.read()
    except FileNotFoundError:
        old = ""
    if new == old:
        return 0
    if "--check" in sys.argv:
        print("INDEX.md is out of date - run: python scripts/build_index.py")
        return 1
    with open(INDEX, "w", encoding="utf-8", newline="\n") as f:
        f.write(new)
    print("INDEX.md updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
